name: amplicon-consensus
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - fastp=0.23.2
  - filtlong=0.2.1
  - nanoq=0.10.0
  - bwa=0.7.17
  - minimap2=2.26
  - samtools=1.18
  - bcftools=1.18
  - qualimap=2.3
  - ivar=1.3
  - freebayes=1.3.7
  - mafft=7.525
